# Generated by Django 5.2.8 on 2026-01-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, null=True, verbose_name='프로필 이미지 URL'),
        ),
    ]
