"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(override=True, dotenv_path=BASE_DIR.parent.parent / ".env")

# ------------------------------------------------------------------------
# [경로 추가] Django에서 'backend' 모듈을 찾을 수 있도록 프로젝트 루트 추가
# ------------------------------------------------------------------------
# BASE_DIR = backend/django
# BASE_DIR.parent = backend
# BASE_DIR.parent.parent = 프로젝트 루트
project_root = BASE_DIR.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
# ------------------------------------------------------------------------

# Docker 환경에서 Fuseki URL 설정
# Docker Compose에서 같은 네트워크의 서비스는 서비스 이름으로 접근 가능
# 로컬 실행 시: http://localhost:3030/korean-history
# Docker 실행 시: http://fuseki:3030/korean-history
if not os.getenv("FUSEKI_URL"):
    # Docker 컨테이너 내부에서 실행 중인지 확인
    # /proc/self/cgroup 파일이 있고 docker가 포함되어 있으면 Docker 환경
    is_docker = False
    try:
        with open("/proc/self/cgroup", "r") as f:
            if "docker" in f.read():
                is_docker = True
    except (FileNotFoundError, IOError):
        pass
    
    # 환경 변수로도 확인 (docker-compose.yml에서 설정 가능)
    if os.getenv("DOCKER_ENV") == "true" or is_docker:
        os.environ["FUSEKI_URL"] = "http://fuseki:3030/korean-history"
    else:
        os.environ["FUSEKI_URL"] = "http://localhost:3030/korean-history"


def env_required(key: str) -> str:
    """Read required environment variable or raise to avoid leaking defaults."""
    value = os.getenv(key)
    if value is None:
        raise RuntimeError(f"Environment variable {key} is required but not set.")
    return value


# LOGGING 설정 추가
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'chatbot': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-^(y!in_zzm#qzjwgk-*a8t*$c^i!$ldk)p7b6b6e*2p@z@n_q2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h] or []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

# rest framework 및 corsheaders

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

# spectacular
    'drf_spectacular',


    # allauth

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # 우리 앱들
    'users',         # 인증 + 프로필 + 관리
    'video',         # 영상 관리
    'activity',      # 검색 + 시청 기록
    'community',     # 댓글 + 답글 + 좋아요
    'chatbot',       # 챗봇
    'game',          # MinjiRun 게임
]

SITE_ID = 1

# 커스텀 User 모델 사용 (auth_user 대체)
AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = 'http://localhost:3000/'
LOGOUT_REDIRECT_URL = 'http://localhost:3000/'
ACCOUNT_LOGOUT_REDIRECT_URL = 'http://localhost:3000/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'config.middleware.CorsMediaMiddleware',  # Media 파일 CORS 헤더 추가
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # No custom templates - React handles all UI
        'APP_DIRS': True,  # Keep True for Django admin templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env_required('POSTGRES_DB'),
        'USER': env_required('POSTGRES_USER'),
        'PASSWORD': env_required('POSTGRES_PASSWORD'),
        'HOST': env_required('POSTGRES_HOST'),
        'PORT': env_required('POSTGRES_PORT'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),  # 기본은 AllowAny
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Redis 캐시 설정 (최소 사용 - 프로필 조회만 캐싱)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{os.getenv("REDIS_HOST", "localhost")}:{os.getenv("REDIS_PORT", "6379")}/{os.getenv("REDIS_DB", "0")}',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'skn18',  # 프로젝트별 키 prefix
        'TIMEOUT': 300,  # 기본 TTL 5분
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-allauth 설정
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'  # OAuth redirect URI를 HTTPS로 생성
SOCIALACCOUNT_LOGIN_ON_GET = True  # 중간 확인 페이지 없이 바로 Google 로그인으로 이동
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 이메일 인증 건너뛰기 (소셜 로그인이므로 불필요)
SOCIALACCOUNT_AUTO_SIGNUP = True  # 소셜 로그인 시 자동 가입

# ============================================
# 커스텀 User 모델 (email 기반) 설정
# ============================================
# username 필드를 사용하지 않음 (우리 User 모델에는 username이 없음)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

# email을 인증 방식으로 사용
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True

# CORS 설정
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://d2lr1p20b7dwp0.cloudfront.net",  # CloudFront Distribution
    "http://www.histok.info",
    "https://www.histok.info",
    "http://histok.info",
    "https://histok.info",
    "https://api.histok.info",  # Backend API subdomain
]

CORS_ALLOW_CREDENTIALS = True

# CORS 허용 헤더 추가
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'connection',
]

# Media 파일(영상 등)에 CORS 헤더 허용
CORS_ALLOW_ALL_ORIGINS = False  # 전체는 허용 안함
CORS_EXPOSE_HEADERS = ['Content-Type', 'Content-Length', 'Accept-Ranges', 'Content-Range']

# CSRF 신뢰 Origin 설정
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://d2lr1p20b7dwp0.cloudfront.net",  # CloudFront Distribution
    "http://www.histok.info",
    "https://www.histok.info",
    "http://histok.info",
    "https://histok.info",
    "https://api.histok.info",  # Backend API subdomain
]

# Google OAuth 스코프 설정

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # APP 설정을 제거하고 데이터베이스의 Social App만 사용
        # (settings.py의 APP과 DB의 Social App이 중복으로 인식되는 문제 방지)
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            # offline + consent: refresh_token을 받을 가능성을 높임
            'access_type': 'offline',
            'prompt': 'consent',
        },
    }
}

# AllAuth 커스텀 어댑터 설정
SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'

# 소셜 토큰을 DB에 저장 (socialaccount_socialtoken)
SOCIALACCOUNT_STORE_TOKENS = True

# 배경 파일(이미지/영상) 저장 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 유니티가 접속할 내 서버(local) 주소
MY_SERVER_URL = "http://127.0.0.1:8000"
# Celery 앱 설정
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# macOS에서 SIGSEGV 오류 방지: prefork 대신 solo 또는 threads 사용
# torch, transformers 같은 대용량 라이브러리 사용 시 prefork 방식이 문제 발생
import sys
if sys.platform == "darwin":  # macOS
    CELERY_WORKER_POOL = "solo"  # 또는 "threads"
else:
    CELERY_WORKER_POOL = "prefork"  # Linux에서는 prefork 사용 가능

# ------------------------------------------------------------------------
# HTTPS/SSL Settings for Production (ALB behind HTTPS)
# ------------------------------------------------------------------------
# ALB에서 HTTPS로 받고 HTTP로 백엔드에 전달하는 경우
# Django가 HTTPS를 인식하도록 설정
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# X-Forwarded-Host 헤더 신뢰 (ALB가 원래 호스트 전달)
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# ------------------------------------------------------------------------
# AWS S3 Storage Settings
# ------------------------------------------------------------------------
# S3 사용 여부 (환경변수로 제어, 기본값은 로컬 스토리지 사용)
USE_S3 = os.getenv('USE_S3', 'False').lower() == 'true'

if USE_S3:
    # S3 버킷 이름
    AWS_STORAGE_BUCKET_NAME_VIDEOS = os.getenv('AWS_S3_BUCKET_VIDEOS', 'skn18-3-dev-videos')
    AWS_STORAGE_BUCKET_NAME_THUMBNAILS = os.getenv('AWS_S3_BUCKET_THUMBNAILS', 'skn18-3-dev-thumbnails')
    AWS_STORAGE_BUCKET_NAME_PROFILES = os.getenv('AWS_S3_BUCKET_PROFILES', 'skn18-3-dev-profiles')

    # AWS 자격 증명 (ECS Task Role 사용 시 불필요, 로컬 테스트용)
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')

    # S3 설정
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION', 'ap-northeast-2')
    AWS_S3_FILE_OVERWRITE = False  # 같은 이름 파일 덮어쓰기 방지
    AWS_DEFAULT_ACL = None  # ACL 비활성화 (버킷 정책으로 관리)
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_QUERYSTRING_AUTH = False  # URL에 인증 쿼리스트링 제거 (public 버킷용)

    # S3 URL 설정
    AWS_S3_CUSTOM_DOMAIN_VIDEOS = f'{AWS_STORAGE_BUCKET_NAME_VIDEOS}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    AWS_S3_CUSTOM_DOMAIN_THUMBNAILS = f'{AWS_STORAGE_BUCKET_NAME_THUMBNAILS}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    AWS_S3_CUSTOM_DOMAIN_PROFILES = f'{AWS_STORAGE_BUCKET_NAME_PROFILES}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

    # 기본 스토리지를 S3로 설정 (프로필 이미지용)
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': AWS_STORAGE_BUCKET_NAME_PROFILES,
                'location': '',  # 버킷 루트에 저장
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
        # 커스텀 스토리지 (영상, 썸네일용)
        'videos': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': AWS_STORAGE_BUCKET_NAME_VIDEOS,
                'location': '',
            },
        },
        'thumbnails': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': AWS_STORAGE_BUCKET_NAME_THUMBNAILS,
                'location': '',
            },
        },
    }

    # Media URL을 S3 URL로 변경
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN_PROFILES}/'

    # storages 앱 추가
    if 'storages' not in INSTALLED_APPS:
        INSTALLED_APPS.append('storages')
