# Generated by Django 5.2.8 on 2026-01-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='WatchingHistory',
        ),
        migrations.AddField(
            model_name='video',
            name='recommended_keyword',
            field=models.TextField(blank=True, null=True, verbose_name='추천 키워드 (쉼표 구분)'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True, verbose_name='썸네일 URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_keyword',
            field=models.TextField(blank=True, null=True, verbose_name='영상 키워드 (쉼표 구분)'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='영상 URL'),
        ),
    ]
