<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-12-30 06:05
=======
# Generated by Django 5.2.8 on 2026-01-03 04:59
>>>>>>> dev

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_delete_comment_delete_likes_delete_reply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'managed': True, 'ordering': ['-upload_date'], 'verbose_name': '영상', 'verbose_name_plural': '영상들'},
        ),
    ]
