# Generated by Django 5.2.8 on 2026-01-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_options'),
    ]

    operations = [
        # init.sql에서 이미 컬럼이 생성되어 있으므로, 모델 상태만 업데이트
        # 실제 컬럼 추가는 하지 않음 (이미 존재)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스에는 이미 컬럼이 있으므로 아무 작업도 하지 않음
            ],
            state_operations=[
                migrations.AddField(
                    model_name='video',
                    name='recommended_keyword',
                    field=models.TextField(blank=True, null=True, verbose_name='추천 키워드 (쉼표 구분)'),
                ),
                migrations.AddField(
                    model_name='video',
                    name='thumbnail_url',
                    field=models.TextField(blank=True, null=True, verbose_name='썸네일 URL'),
                ),
                migrations.AddField(
                    model_name='video',
                    name='video_keyword',
                    field=models.TextField(blank=True, null=True, verbose_name='영상 키워드 (쉼표 구분)'),
                ),
                migrations.AddField(
                    model_name='video',
                    name='video_url',
                    field=models.TextField(verbose_name='영상 URL'),
                ),
            ],
        ),
    ]
