# Generated by Django 5.2.8 on 2025-12-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True, verbose_name='썸네일 URL'),
        ),
    ]
