# Generated by Django 5.2.8 on 2026-01-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_thumbnail_url_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='영상 URL'),
        ),
    ]
