# Generated by Django 5.2.8 on 2026-01-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': '검색 기록', 'verbose_name_plural': '검색 기록들'},
        ),
        migrations.AlterModelOptions(
            name='watchinghistory',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': '시청 기록', 'verbose_name_plural': '시청 기록들'},
        ),
    ]
