# Generated by Django 5.2.8 on 2026-01-03 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_searchhistory_options_and_more'),
        ('video', '0004_video_recommended_keyword_video_thumbnail_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # init.sql에서 이미 컬럼이 생성되어 있으므로, 모델 상태만 업데이트
        # 실제 컬럼 추가는 하지 않음 (이미 존재)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스에는 이미 컬럼이 있으므로 아무 작업도 하지 않음
            ],
            state_operations=[
                migrations.AddField(
                    model_name='searchhistory',
                    name='user',
                    field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
                ),
                migrations.AddField(
                    model_name='watchinghistory',
                    name='recommended_keyword',
                    field=models.TextField(blank=True, null=True, verbose_name='추천 키워드'),
                ),
                migrations.AddField(
                    model_name='watchinghistory',
                    name='user',
                    field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
                ),
                migrations.AddField(
                    model_name='watchinghistory',
                    name='video',
                    field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to='video.video', verbose_name='영상'),
                ),
                migrations.AddField(
                    model_name='watchinghistory',
                    name='video_keyword',
                    field=models.TextField(blank=True, null=True, verbose_name='영상 키워드'),
                ),
                migrations.AlterField(
                    model_name='watchinghistory',
                    name='tags',
                    field=models.TextField(blank=True, null=True, verbose_name='태그'),
                ),
            ],
        ),
    ]
