# Generated by Django 5.2.8 on 2025-12-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField(verbose_name='검색어')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검색일')),
            ],
            options={
                'verbose_name': '검색 기록',
                'verbose_name_plural': '검색 기록들',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
