# Generated by Django 5.2.8 on 2026-01-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글들'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': '좋아요', 'verbose_name_plural': '좋아요들'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'managed': True, 'ordering': ['created_at'], 'verbose_name': '답글', 'verbose_name_plural': '답글들'},
        ),
    ]
