# Generated by Django 5.2.8 on 2026-01-03 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_comment_options_alter_likes_options_and_more'),
        ('video', '0004_video_recommended_keyword_video_thumbnail_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # init.sql에서 이미 컬럼이 생성되어 있으므로, 모델 상태만 업데이트
        # 실제 컬럼 추가는 하지 않음 (이미 존재)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # 데이터베이스에는 이미 컬럼이 있으므로 아무 작업도 하지 않음
            ],
            state_operations=[
                migrations.AddField(
                    model_name='comment',
                    name='user',
                    field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
                ),
                migrations.AddField(
                    model_name='comment',
                    name='video',
                    field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video.video', verbose_name='영상'),
                ),
                migrations.AddField(
                    model_name='likes',
                    name='comment',
                    field=models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.comment', verbose_name='댓글'),
                ),
                migrations.AddField(
                    model_name='likes',
                    name='reply',
                    field=models.ForeignKey(blank=True, db_column='reply_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.reply', verbose_name='답글'),
                ),
                migrations.AddField(
                    model_name='likes',
                    name='user',
                    field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
                ),
                migrations.AddField(
                    model_name='likes',
                    name='video',
                    field=models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='video.video', verbose_name='영상'),
                ),
                migrations.AddField(
                    model_name='reply',
                    name='comment',
                    field=models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment', verbose_name='댓글'),
                ),
                migrations.AddField(
                    model_name='reply',
                    name='parent_reply',
                    field=models.ForeignKey(blank=True, db_column='parent_reply_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='community.reply', verbose_name='부모 답글'),
                ),
                migrations.AddField(
                    model_name='reply',
                    name='user',
                    field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
                ),
            ],
        ),
    ]
