# Generate된 답변의 말투 교정하는 노드
from langgraph.graph import END
from backend.langgraph_structure1.state import GraphState
from backend.langgraph_structure1.utils import create_model
from celery.utils.log import get_task_logger

logger = get_task_logger(__name__)

def tone_adjust_node(state: GraphState) -> GraphState:
    """
    말투 교정 노드
    """
    final_answer = state.get("final_answer", "")
    tag = state.get("tag", "reply")
    lang = state.get("detect_lang", "ko")

    if not final_answer:
        raise ValueError("tone_adjust_node: 'final_answer' 값이 state에 없습니다.")
    
    # [안전장치 1] 변수 초기화 (에러 방지)
    TONE_PROMPT = ""
    
    if lang == "ko":
        user_content = f"""
        아래 내용은 이미 완성된 정답입니다.
        내용은 절대 바꾸지 마세요.

        시스템 지침과 [규칙]을 엄격히 따라
        말투와 표현만 바꿔 주세요.
        새로운 내용은 절대 추가하지 마세요.

        [입력]
        {final_answer}
        """.strip()

        if tag == "chat":
            TONE_PROMPT = """
            SYSTEM:
            당신은 말투와 표현 수준만 바꾸는 도우미입니다.
            다른 시스템이 만든 조선 시대 역사 답변을 초등학생도 이해할 수 있게 바꿉니다.

            [내용 불변 규칙]
            - 입력된 텍스트는 최종 정답이므로 절대 바꾸지 마세요.
            - 추가, 삭제, 요약, 순서 변경, 해석 변경은 모두 금지입니다.
            - 의미와 흐름을 그대로 두고, 말만 쉽게 바꾸세요.

            [규칙]
            1. 아주 쉬운 한국어만 사용하세요.
            2. 문장은 짧게 쓰고, 한 문장에 한 가지 내용만 담으세요.
            3. 말투는 친구에게 설명해 주듯 자연스럽게 하되, 반말은 사용하지 마세요.
            4. 대화문이나 이야기처럼 쓰지 마세요.
            5. 규칙을 설명하지 말고, 바뀐 설명문만 출력하세요.
            6. 어려운 단어는 쉬운 말로 풀어쓰되, 새 정보를 추가하지 마세요.
            """.strip()
            
        elif tag == "reply":
            TONE_PROMPT = """
            SYSTEM:
            당신은 말투 조정 도우미입니다. 
            다른 시스템이 만든 정답 내용을 받아, 짧고 친근한 한국어 답글로 바꿉니다.

            [내용 불변 규칙]
            - 입력된 내용은 이미 완성된 정답입니다.
            - 내용을 추가, 삭제, 고치거나 새로 해석하지 마세요.
            - 뜻은 그대로 두고, 말투와 길이만 바꾸세요.

            [규칙]
            1. 한국어만 사용하세요.
            2. 2~3줄로 아주 짧게 답하세요.
            3. 초등학생도 이해할 수 있는 쉬운 말만 쓰세요.
            4. 말투는 친구에게 설명해 주듯 자연스럽고 다정하게 하되, 반말은 사용하지 마세요.
            5. 새로운 설명이나 정보는 절대 넣지 마세요.
            6. 어려운 단어는 쉬운 말로 풀어쓰되, 새 정보를 추가하지 마세요.
            7. 답변 문장만 출력하세요.
            """.strip()

        # [수정됨] 비디오 태그 처리 추가
        elif tag == "video":
            TONE_PROMPT = """
            SYSTEM:
            당신은 역사 다큐멘터리 작가입니다.
            입력된 내용을 바탕으로 영상 제작을 위한 '나레이션 대본' 스타일로 다듬습니다.
            
            [규칙]
            1. 시청자에게 이야기하듯이 자연스러운 구어체(해요체/하십시오체 혼용)를 사용하세요.
            2. 문장은 호흡이 너무 길지 않게 끊어주세요.
            3. 어려운 한자어보다는 귀에 잘 들리는 쉬운 표현을 쓰세요.
            4. 내용은 왜곡하지 말고 원문을 충실히 따르세요.
            """.strip()
        
        # [안전장치 2] 알 수 없는 태그일 때 기본값
        else:
            TONE_PROMPT = "SYSTEM: 내용을 이해하기 쉽게 다듬어주세요."

    elif lang == "en":
        user_content = f"""
        The following text is a correct answer generated by another system.
        Do NOT change the content.

        Please rewrite it according to the system instructions.
        Change ONLY the tone, language level, and style.
        Do NOT add, remove, or modify any information.

        [Input]
        {final_answer}
        """.strip()

        if tag == "chat":
            TONE_PROMPT = """
            SYSTEM:
            You are a style and language converter. You receive a correct Korean-history answer generated by another system and rewrite it into simple English for foreign learners.

            [CONTENT IMMUTABILITY RULE]
            - The input text is the final, correct answer.
            - Do NOT change content in any way: no additions, deletions, corrections, summaries, or reordering.
            - Only convert language level and tone while preserving exact meaning and structure.

            [RULES]
            1. Convert all content into simple English (CEFR B1–B2).
            2. Keep factual accuracy and logical order exactly the same.
            3. Proper nouns must be written as:
            Romanized Korean name (English explanation).
            - Example: Joseon (the Joseon Dynasty)
            - Example: Sejong (King Sejong)
            4. Explain a proper noun in parentheses only at its first appearance.
            5. If the input contains Korean inside parentheses, translate it and keep ENGLISH ONLY inside the parentheses.
            6. Final output must contain ENGLISH ONLY. No Korean characters.
            7. Use explanatory text only. No dialogue or storytelling.
            8. Output only the rewritten English text.
            9. Use a warm, friendly, natural, conversational tone as if explaining to a friend, but avoid slang or overly casual expressions.
            """.strip()
          
        elif tag == "reply":
            TONE_PROMPT = """
            SYSTEM:
            You are a tone-adjustment assistant. You receive a correct answer generated by another system and rewrite it as a short, friendly English reply.

            [CONTENT IMMUTABILITY RULE]
            - The input text is the final correct answer.
            - Do NOT add, remove, correct, summarize, expand, reorder, or reinterpret any information.
            - Change ONLY tone, wording, and length.
            - Preserve the exact meaning and intent.

            [RULES]
            1. Output ENGLISH ONLY.
            2. Limit the reply to 2–3 short lines.
            3. Use a warm, friendly, natural, conversational tone as if explaining to a friend, but avoid slang or overly casual expressions.
            4. Do NOT introduce new facts or explanations.
            5. If Korean historical names appear, keep:
            Romanized name (short English explanation).
            - Example: Sejong (a Joseon king who created Hangul(Korean alphabet))
            6. Output only the rewritten reply text.
            """.strip()

        # [수정됨] 비디오 태그 처리 추가 (영어)
        elif tag == "video":
            TONE_PROMPT = """
            SYSTEM:
            You are a documentary scriptwriter.
            Rewrite the text into an engaging narration script.
            Use clear, spoken English suitable for a general audience.
            """.strip()

        # [안전장치 2] 알 수 없는 태그일 때 기본값
        else:
             TONE_PROMPT = "SYSTEM: Rewrite the text to be clear and easy to understand."

    # LLM 호출
    client = create_model()
    MODEL_NAME = "gpt-4o-mini" # 모델명은 상황에 맞게 변경 (ex: gpt-5-mini가 있다면 그걸로)

    # [안전장치 3] 프롬프트 누락 방지
    if not TONE_PROMPT:
        TONE_PROMPT = "SYSTEM: Please refine the following text."

    response = client.chat.completions.create(
        model=MODEL_NAME,
        response_format={"type": "text"},
        messages=[
            {"role": "system", "content": TONE_PROMPT},
            {"role": "user", "content": user_content},
        ],
    )

    transformed_text = response.choices[0].message.content.strip()

    # 결과 터미널 출력
    logger.info("[tone_adjust_node] Transformed Text:\n%s", transformed_text)
    logger.info("-" * 60)

    new_state = {
        **state,
        "tone_corrected_answer": transformed_text,
    }
    
    # [수정됨] 채팅/답글/비디오 모두 교정된 답변을 최종 답변으로 반영
    # 이렇게 해야 다음 노드(scene_split_node)가 '다듬어진 대본'을 가져갈 수 있습니다.
    if tag in ("chat", "reply", "video"):
        new_state["final_answer"] = transformed_text

    return new_state

def route_tone_adjust_node(state: GraphState) -> str:
    """
    tone_adjust_node에서 라우팅하는 함수
    """
    tag = state.get("tag", "")
    
    if tag == "chat" or tag == "reply":
        return END
    elif tag == "video":
        return "scene_split_node"
    
    # 방어 로직: 알 수 없는 태그면 그래프 종료
    return END

if __name__ == "__main__":
    # 테스트 코드 생략 (필요하면 그대로 두셔도 됩니다)
    pass